### ISSUE TITLE
gOriginalPrintChat offset should be taken with a signature scan

### ISSUE THREAD

**Issue by luxalpa** [ur0/DotATranslator#1]
> gOriginalPrintChat = (int64_t(*) (void *, int, wchar_t*, int))((int64_t)ba + 0x358cc0);

The offset `0x358cc0` here is hardcoded. Instead, you could do what the tools/cheats on unknowncheats do and use a signature scan to always find the function.

https://www.unknowncheats.me/forum/general-programming-and-reversing/133228-implement-pattern-scanning-obtain-offsets-dynamically.html

https://www.unknowncheats.me/forum/666255-post2.html

**Comment by ur0** [comment]
Yep, sounds great. I'm looking for a relatively stable pattern for the function (so far all my options either matched a bunch of functions or would break easily as proven by today's update).
